#!/usr/bin/env python
# coding: utf-8

# In[5]:


import pandas as pd
import pandas_datareader.data as web
import datetime as dt
from datetime import datetime
import os

def get_stock_data():
    os.environ["IEX_API_KEY"] = "pk_96e73946e01b4aa1a4cf9293f65c4169"
    tickers = ['MCD', 'AAPL']

    start = dt.datetime(2020,2,5)
    end = dt.datetime.today()

    if not os.path.exists('stockdata'):
        os.makedirs('stockdata')

    for ticker in tickers:
        print(ticker)
        try :
            df = web.DataReader(ticker, "iex", start, end)
            print(df.head())
            df.to_csv('stockdata/{}.csv'. format(ticker))
            print(ticker, 'download')
        except Exception as e:
            print(e, 'error')

get_stock_data()


# In[ ]:
